Controllers/BrokersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;
using project.ViewModels;

namespace project.Controllers
{
    public class BrokersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;

        public BrokersController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: Brokers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Broker.ToListAsync());
        }

      

        // GET: Brokers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brokers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrokerId,FirstName,LastName,Email,Phonenumber,Image,ImageText,HomeId, Title")] Broker broker, bool HeroImage2, BrokersViewModel model)
        {
            if (ModelState.IsValid)
            {



                //en bild
                string uniqueFileName = null;
                if (model.Photo != null)

                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.Photo.FileName);
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));

                    
                    broker.Image = uniqueFileName;
                }


            




                _context.Add(broker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(broker);
        }

        // GET: Brokers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var broker = await _context.Broker.FindAsync(id);
            if (broker == null)
            {
                return NotFound();
            }
            return View(broker);
        }

        // POST: Brokers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BrokerId,FirstName,LastName,Email,Phonenumber,Image,ImageText,HomeId, Title")] Broker broker, BrokersViewModel model)
        {
            if (id != broker.BrokerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //en bild
                    string uniqueFileName = null;
                    if (model.Photo != null)

                   {
                        string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                        uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.Photo.FileName);
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));

                        /*
                                                Broker img = new Broker();
                                                img.ImageText = uniqueFileName;
                                                img.Image = uniqueFileName;


                                                _context.Update(img);
                                                */
                        broker.Image = uniqueFileName;
                    }

                 
                    _context.Update(broker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrokerExists(broker.BrokerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(broker);
        }

        // GET: Brokers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var broker = await _context.Broker
                .FirstOrDefaultAsync(m => m.BrokerId == id);
            if (broker == null)
            {
                return NotFound();
            }

            return View(broker);
        }

        // POST: Brokers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var broker = await _context.Broker.FindAsync(id);
            _context.Broker.Remove(broker);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrokerExists(int id)
        {
            return _context.Broker.Any(e => e.BrokerId == id);
        }
    }
}

Controllers/HomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;
using System.Web;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using project.ViewModels;

namespace project.Controllers
{
    public class HomesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;

        public HomesController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
        }


        // GET: Homes
        [Authorize]
        public async Task<IActionResult> Index()
        {

            return View(await _context.Homes.ToListAsync());

        }

        // GET: Homes/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id, int BrokerId)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.BrokId = BrokerId;

            /* IMAGES */
            var getImages = _context.Image;
            // ALL REGULAR IMAGES

            List<Image> HomeImage = new List<Image>();
            foreach (var item in getImages)
            {
                if (item.HomeIds == id)
                {
                    if (item.HeroImage != true && item.FloorPlan != "true")
                    {
                        Image imgs = new Image()
                        {
                            ImageText = item.ImageText,
                            ImageAdress = item.ImageAdress,
                            ImageId = item.ImageId

                        };
                        HomeImage.Add(imgs);
                    }
                }
            }

            ViewBag.HomeImg = HomeImage;
            

            // HERO IMAGE
           List<Image> HeroImages = new List<Image>();
            foreach (var item in getImages)
            {
                if (item.HomeIds == id && item.HeroImage == true)
                {
                    Image Herimgs = new Image()
                    {
                        ImageText = item.ImageText,
                        ImageAdress = item.ImageAdress,
                        ImageId = item.ImageId
                    };
                    HeroImages.Add(Herimgs);
                }
            }
            ViewBag.HeroImages = HeroImages;
            

            // ALL FLOORPLANS
            List<Image> Planritning = new List<Image>();
            foreach (var item in getImages)
            {
                if (item.HomeIds == id)
                {
                    if (item.FloorPlan == "true")
                    {
                        Image imgs = new Image()
                        {
                            ImageText = item.ImageText,
                            ImageAdress = item.ImageAdress,
                            ImageId = item.ImageId

                        };
                        Planritning.Add(imgs);
                    }
                }
            }
            ViewBag.Planritning = Planritning;
            // BROKERS

            var brokers = _context.Broker;
            List<Broker> Brokers = new List<Broker>();
            foreach (var item in brokers)
            {
                if (BrokerId == item.BrokerId)
                {
                    Broker brok = new Broker()
                    {
                        BrokerId = item.BrokerId,
                        FirstName = item.fullname,
                        Phonenumber = item.Phonenumber,
                        Email = item.Email,
                        Title = item.Title,
                        Image = item.Image
                    };
                    Brokers.Add(brok);
                }
            }
            ViewBag.BrokerList = Brokers;



            var homes = await _context.Homes
                .FirstOrDefaultAsync(m => m.HomeId == id);
            if (homes == null)
            {
                return NotFound();
            }

            return View(homes);
        }

        // GET: Homes/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.BrokersId = new SelectList(_context.Broker, "BrokerId", "fullname");
            return View();
        }


        // POST: Homes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HomeId,PublishDate,Type,Street,City,County,PostalCode,District Room,AppartmentNumber,Society,Floor,Elevator,Dop,Price,Bidding,HomeType,Tow,LivingArea,BiArea,GardenArea,Floor,BuildningSystem,Renovations,OtherBuildnings,LivingSpaceComment,Parking,TvInternet,HeatVentilation,BuildningYear,MounthlyFee,PartOfSociety,PawnBroking,AboutSociety,CommonAreas,TransactionFee,TransactionFeePaidBy,OperationCost,TypeCode,TaxValue,TaxValueProperty,TaxValueLand,TaxYear,PawnLetters,Heating,PowerComsumption,EnergyCosts,NumberOfOccupants,WaterAndSewedge,Cleaning,Insurance,InsuranceComment,EnergyDeclaration,EnergyPerfomance,EnergyClass,SpecificEnergyUsage,DeclarationDate,Inspector,SummaryHeading,Summary,Information, OtherRightsAndLiabilities")]Homes homes, string ImageText2, bool HeroImage2, HomesCreateViewModel model, int Brokers)
        {
   
            if (ModelState.IsValid)
            {

                // GET "HomeId" to use for the images 
                int maxId = 0;

                if (_context.Homes.Any(u => u.HomeId >= 1)) // I ANY HOMES EXISTS 
                {
                    maxId = (from c in _context.Homes select c.HomeId).Max(); // GET HIGHEST ID
                }
                else
                {
                    maxId = 0; // IF NO HOMES EXISTS, DECLARE maxID TO 0
                }

                int newId = maxId + 1; // ADD 1 

                //ONE IMAGE
                string uniqueFileName = null;
                string uniqueFileNames = null;
                if (model.Photo != null)

                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileNames = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.Photo.FileName);
                    string filePath = Path.Combine(uploadsFolder, uniqueFileNames);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));


                    Image img = new Image();
                    img.ImageText = ImageText2;
                    img.ImageAdress = uniqueFileNames;
                    img.HeroImage = HeroImage2;
                    img.FloorPlan = "false";
                    img.HomeIds = newId;

                    _context.Add(img);
                }


                int i = 0;
                int k = 0;

                //MULTIPLE IMAGES

                if (model.Photos != null && model.Photos.Count > 0)
                {

                    foreach (IFormFile photo in model.Photos)
                    {


                        int b = i++;
                        int c = k++;

                        string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                        uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(photo.FileName);
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        photo.CopyTo(new FileStream(filePath, FileMode.Create));


                        Image img = new Image();
                        string formInput = Request.Form["Multiple"];
                        string[] imgText = formInput.Split(',');


                        string formInput2 = Request.Form["Floorplan3"];
                        //
                        string[] floorplans = formInput2.Split(',');

                        img.ImageText = imgText[b];
                        img.ImageAdress = uniqueFileName;
                        img.HeroImage = false;
                        img.FloorPlan = floorplans[c];
                        img.HomeIds = newId;

                        _context.Add(img);

                    }
                }
                homes.deleted = false;
                homes.ImageAddress = uniqueFileNames;
                homes.BrokerId = Brokers;
                _context.Add(homes);


                ViewBag.BrokersId = new SelectList(_context.Broker, "BrokerId", "fullname");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //  return View(model);
            }
            ViewBag.BrokersId = new SelectList(_context.Broker, "BrokerId", "fullname");
            return View(model);
        }

        // GET: Homes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id, HomesCreateViewModel test)
        {
            if (id == null)
            {
                return NotFound();
            }
            var getImages = _context.Image;
            // HERO IMAGE
            List<Image> HeroImages = new List<Image>();
            foreach (var item in getImages)
            {
                if (item.HomeIds == id && item.HeroImage == true)
                {
                    Image Herimgs = new Image()
                    {
                        ImageText = item.ImageText,
                        ImageAdress = item.ImageAdress,
                        ImageId = item.ImageId
                    };
                    HeroImages.Add(Herimgs);
                }
            }

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="sv">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ekfeldt & Co</title>
    <meta charset="utf-8">
    <script src="https://kit.fontawesome.com/08fc0a0a1d.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Lora&display=swap" rel="stylesheet">
    <script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js" charset="utf-8"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.8/fullpage.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3" id="menu">
            <div class="container">
                <a class="navbar-brand logo text-white" asp-area="" asp-controller="Home" asp-action="Index">Ekfeldt & Co</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Startsida</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="TillSalu">Tillsalu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Kopa">Sälja</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Homes" asp-action="Index">Objekt</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Brokers" asp-action="Index">Mäklare</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Biddings" asp-action="Index">Budgivningar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Demonstrations" asp-action="Index">Visningar</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

    </header>
        @RenderBody()
        <footer class="section fp-auto-height">
            <div class="container">
                <h1>Ekfeldt & Co</h1>
                <hr />
                <div class="row">
                    <div class="col-md-4">
                        <h2>Kontakt</h2>
                        <ul>

                            <li>Mäklargatan 10</li>
                            <li>31 655, Mäkleborg</li>
                            <li>Telefon kontor: 0648-84612</li>

                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h2>Öppettider</h2>
                        <ul>


                            <li>Mån - fre: 10.00-18.00</li>
                            <li>Lör - sön: 10.00-15.00</li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h2>Följ oss</h2>
                        <ul>


                            <li>
                                <i class="fab fa-instagram"></i>
                            </li>
                            <li><i class="fab fa-facebook"></i></li>
                        </ul>
                    </div>

                </div>
                <hr />
                <div class="btmFooter">
                    <p>
                        © Rebecca Seiron &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;A <a href="https://webuals.com/">Webuals</a> production |
                        &nbsp;&nbsp;&nbsp;&nbsp; @if (SignInManager.IsSignedIn(User))
                        {
                            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <input type="submit" class="nav-link btn btn-link text-dark" value="Logga ut" />
                            </form>
                        }
                        else
                        {<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Logga in</a>}
                    </p>
                </div>
            </div>
        </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.8/fullpage.min.js"></script>
    <script>
        new fullpage('#fullpage', {
            //options here
            autoScrolling: true,
            scrollHorizontally: true,
            navigation: true,
            navigationPosition: 'left',

        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>