Controllers/DemonstrationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;

namespace project.Controllers
{
    public class DemonstrationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DemonstrationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Demonstrations
        public async Task<IActionResult> Index()
        {
          
            return View(await _context.Demonstration.ToListAsync());
        }

        // GET: Demonstrations/Details/5
        public async Task<IActionResult> Details(int? id, int? homeId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var home = from t in _context.Homes
                       where t.HomeId == homeId
                       select t.FullAddress.ToString();
            ViewBag.home = home;
            var demonstration = await _context.Demonstration
                .FirstOrDefaultAsync(m => m.DemonstrationId == id);
            if (demonstration == null)
            {
                return NotFound();
            }

            return View(demonstration);
        }

        // GET: Demonstrations/Create
        public IActionResult Create()
        {
            ViewBag.Homes = new SelectList(_context.Homes, "HomeId", "FullAddress");
            return View();
        }

        // POST: Demonstrations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DemonstrationId,BookingTime,BookingDate,HomeId")] Demonstration demonstration)
        {
            ViewBag.Homes = new SelectList(_context.Homes, "HomeId", "FullAddress");
            if (ModelState.IsValid)
            {
                _context.Add(demonstration);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(demonstration);
        }

        // GET: Demonstrations/Edit/5
        public async Task<IActionResult> Edit(int? id, int? homeId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var home = from t in _context.Homes
                       where t.HomeId == homeId
                       select t.FullAddress.ToString();
            ViewBag.home = home;
            var demonstration = await _context.Demonstration.FindAsync(id);
            if (demonstration == null)
            {
                return NotFound();
            }
            return View(demonstration);
        }

        // POST: Demonstrations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DemonstrationId,BookingTime,BookingDate,FirstName,LastName,Street,City,PostalCode,District,PhoneNUmber,Email,HomeId")] Demonstration demonstration)
        {
            if (id != demonstration.DemonstrationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(demonstration);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DemonstrationExists(demonstration.DemonstrationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(demonstration);
        }

        // GET: Demonstrations/Delete/5
        public async Task<IActionResult> Delete(int? id, int? homeId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var home = from t in _context.Homes
                       where t.HomeId == homeId
                       select t.FullAddress.ToString();
            ViewBag.home = home;

            var demonstration = await _context.Demonstration
                .FirstOrDefaultAsync(m => m.DemonstrationId == id);
            if (demonstration == null)
            {
                return NotFound();
            }

            return View(demonstration);
        }

        // POST: Demonstrations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var demonstration = await _context.Demonstration.FindAsync(id);
            _context.Demonstration.Remove(demonstration);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DemonstrationExists(int id)
        {
            return _context.Demonstration.Any(e => e.DemonstrationId == id);
        }
    }
}

Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;

namespace project.Controllers
{

        public class PersonsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonsController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Persons
        public async Task<IActionResult> Index(int? homeId)
        {
            var demos = _context.Persons;
            List<Persons> pers = new List<Persons>();

            if (homeId != null)
            {

                foreach (var item in demos)
                {
                    if (item.HomeId == homeId && item.Viewer == true && item.deleted != true)
                    {
                        Persons person = new Persons()
                        {
                            PersonId = item.PersonId,
                            FirstName = item.FirstName,
                            LastName = item.LastName,
                            PhoneNUmber = item.PhoneNUmber,
                            Email = item.Email,
                            City = item.City,
                            Street = item.Street,
                            PostalCode = item.PostalCode,
                            HomeId = item.HomeId

                        };
                        pers.Add(person);
                        ViewBag.demosControll = 1;
                        ViewBag.persons = pers;
                    }

                }
                // GET OBJECT ADDRESS
                var home = from t in _context.Homes
                           where t.HomeId == homeId
                           select t.FullAddress.ToString();
                ViewBag.home = home;
            }

            return View(await _context.Persons.ToListAsync());
        }
        public async Task<IActionResult> BidderIndex(int? homeId)
        {
            var demos = _context.Persons;
            List<Persons> pers = new List<Persons>();

            if (homeId != null)
            {

                foreach (var item in demos)
                {
                    if (item.HomeId == homeId && item.Bidder == true && item.deleted != true)
                    {
                        Persons person = new Persons()
                        {
                            PersonId = item.PersonId,
                            FirstName = item.FullName,
                            LastName = item.LastName,
                            PhoneNUmber = item.PhoneNUmber,
                            Email = item.Email,
                            City = item.City,
                            Street = item.Street,
                            PostalCode = item.PostalCode,
                            HomeId = item.HomeId,
                            Amount = item.Amount,
                            Date = item.Date,
                            Time = item.Time

                        };
                        pers.Add(person);
                        ViewBag.demosControll = 1;

             
                    }

                }
            }
            // GET OBJECT ADDRESS
            var home = from t in _context.Homes
                       where t.HomeId == homeId
                       select t.FullAddress.ToString();
            ViewBag.home = home;

            ViewBag.homeId = homeId;
            // CHANGE ORDER ON "INDEXOUTPUT" - HIGHEST BID FIRST

            ViewBag.persons = pers.OrderByDescending(x => x.Amount).ToList();
            return View(await _context.Persons.ToListAsync());
        }

        // GET: Persons/Details/5
        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id, int? demoId, int? HomeId)
        {
            if (id == null)
            {
                return NotFound();
            }
            
         var demos = _context.Demonstration;
            List<Demonstration> Demonstrations = new List<Demonstration>();
            foreach (var item in demos)
            {
                if (item.DemonstrationId == demoId)
                {

                    Demonstration dem = new Demonstration()
                    {
                        DemonstrationId = item.DemonstrationId,
                        BookingDate = item.BookingDate,
                        BookingTime = item.BookingTime

                    };
                    Demonstrations.Add(dem);
                    ViewBag.control = 1;
                }
          
            }

            ViewBag.demos = Demonstrations;

            var home = from t in _context.Homes
                       where t.HomeId == HomeId
                       select t.FullAddress.ToString();
            ViewBag.home = home;

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }


        // GET: Persons/Create
        public IActionResult Create(int? homeId)
        {


            ViewBag.HomeId = homeId;
            ViewBag.homes = new SelectList(_context.Homes, "HomeId", "FullAddress");
            return View();
        }
        public IActionResult CreateBidder(int? homeId, int biddingId)
        {
            var person = _context.Persons;
            List<Persons> persons = new List<Persons>();
            foreach (var item in person)
            {
                if (item.Bidder == true && item.PostalCode != null && item.HomeId == homeId)
                {

                    Persons pers = new Persons()
                    {
                        FirstName = item.FullName,
                        PersonId = item.PersonId


                    };
                    persons.Add(pers);

                }

            }

          
         int? highest = 0;
        
           

            if (_context.Persons.Any(u => u.Amount >= 1))
            {
                highest = (from t in _context.Persons
                           where t.HomeId == homeId

                           select t.Amount).Max();
                int high = Convert.ToInt32(highest);
                ViewBag.high = high;
                if(highest == null)
                {
                    int highests2 = 1;
                    ViewBag.high = highests2;
                }
            }
   

 
            ViewBag.persons = persons;


            ViewBag.homeId = homeId;
            ViewBag.biddingId = biddingId;
            ViewBag.homes = new SelectList(_context.Homes, "HomeId", "FullAddress");
            return View();
        }


        // POST: Persons/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonId,FirstName,LastName,Street,City,PostalCode,Bidder,Viewer,PhoneNUmber,BiddingId, Email")] Persons persons, int DemonstrationId)
        {
       
            string HomeIdt = Request.Form["HomeId"];
            int RealHomeId = Convert.ToInt32(HomeIdt);
            string BrokId = Request.Form["BrokId"];
            int RealBrokerId = Convert.ToInt32(BrokId);
            if (ModelState.IsValid)
            {

                persons.DemonstrationId = DemonstrationId;
                persons.HomeId = RealHomeId;


                _context.Add(persons);
                await _context.SaveChangesAsync();
                ViewBag.msg = "<b>Tack för din anmälan, vi ses på visningen!</b>";
                return Redirect("/Home/Details/" + RealHomeId + "?BrokerId=" + RealBrokerId + "#visning");
            }
            
            return Redirect("/Home/Details/" + RealHomeId + "?BrokerId=" + RealBrokerId +"#visning");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
      
        public async Task<IActionResult> CreateViewer([Bind("PersonId,FirstName,LastName,Street,City,PostalCode,Bidder,Viewer,PhoneNUmber,BiddingId, Email")] Persons persons, int DemonstrationId)
        {

            string HomeIdt = Request.Form["HomeId"];
            int RealHomeId = Convert.ToInt32(HomeIdt);
         
            if (ModelState.IsValid)
            {

                persons.DemonstrationId = DemonstrationId;
                persons.HomeId = RealHomeId;


                _context.Add(persons);
                await _context.SaveChangesAsync();
                ViewBag.msg = "<b>Tack för din anmälan, vi ses på visningen!</b>";
                return Redirect("/Persons?homeId=" + RealHomeId);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBidder([Bind("PersonId,FirstName,LastName,Street,City,PostalCode,Bidder,Viewer,PhoneNUmber,BiddingId, Email, Amount, Date, Time, BiddingIds")] Persons persons, int DemonstrationId, int BiddingIds, int homeId, int? amount, DateTime date, DateTime time, string FirstName, string LastName, string Street, string City, string PostalCode, string PhoneNUmber, string Email)
        {

            string HomeIdt = Request.Form["HomeId"];
            int RealHomeId = Convert.ToInt32(HomeIdt);
  
            if (ModelState.IsValid)
            {

                string pers = Request.Form["persons"];
                int persConv = Convert.ToInt32(pers);

                if (pers != "0")
                {

                    var fname = from t in _context.Persons
                                where t.PersonId == persConv
                                select t.FirstName;
                    foreach(var item in fname)
                    {
                        var fnamex = item;
                       string fnames = fnamex.ToString();

Views/Demonstrations/Create.cshtml
@model project.Models.Demonstration

@{
    ViewData["Title"] = "Lägg till visning";
}
<div class="section">
    <div id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 high social">
                    <ul>
                        <li>
                            <i class="fab fa-instagram"></i>
                        </li>
                        <li><i class="fab fa-facebook"></i></li>
                    </ul>
                </div>
                <div class="col high main">
                    <h1>Lägg till visning</h1>

                </div>
                <div class="col-sm-5 high">
                    <img src="~/images/man.png" alt="En man" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container marginTop">

    <h4>Visning</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="BookingTime" class="control-label"></label>
                    <input type="time" asp-for="BookingTime" class="form-control" />
                    <span asp-validation-for="BookingTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BookingDate" class="control-label"></label>
                    <input type="date" asp-for="BookingDate" class="form-control" />
                    <span asp-validation-for="BookingDate" class="text-danger"></span>
                </div>

       
                <div class="form-group">
                    <label class="control-label">Hem</label>
                    <select asp-for="HomeId" class="form-control" asp-items="ViewBag.Homes"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Skapa" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Gå tillbaka till listan</a>
    </div>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

    <script src="~/js/menu.js"></script>

Views/Demonstrations/Delete.cshtml
@model project.Models.Demonstration

@{
    ViewData["Title"] = "Radera visning";
}

<div class="section">
    <div id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 high social">
                    <ul>
                        <li>
                            <i class="fab fa-instagram"></i>
                        </li>
                        <li><i class="fab fa-facebook"></i></li>
                    </ul>
                </div>
                <div class="col high main">
                    <h1>Radera visning</h1>

                </div>
                <div class="col-sm-5 high">
                    <img src="~/images/man.png" alt="En man" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container marginTop">
    <div>
        <h4>Visning</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingDate)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.HomeId)
            </dt>
            <dd class="col-sm-10">
                @{ foreach (var item in ViewBag.home)
                    {@item
                }
                }
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="DemonstrationId" />
            <input type="submit" value="Radera" class="btn btn-danger" /> |
            <a asp-action="Index">Gå tillbaka</a>
        </form>
    </div>
    </div>
    <script src="~/js/menu.js"></script>

Views/Demonstrations/Details.cshtml
@model project.Models.Demonstration

@{
    ViewData["Title"] = "Detaljer";
}

<div class="section">
    <div id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 high social">
                    <ul>
                        <li>
                            <i class="fab fa-instagram"></i>
                        </li>
                        <li><i class="fab fa-facebook"></i></li>
                    </ul>
                </div>
                <div class="col high main">
                    <h1>Detaljer om visningen</h1>

                </div>
                <div class="col-sm-5 high">
                    <img src="~/images/man.png" alt="En man" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container marginTop">

    <div>
        <h4>Visning</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingDate)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.HomeId)
            </dt>
            <dd class="col-sm-10">
               @{ foreach (var item in ViewBag.home)
                   {@item
                   }
               }
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-homeId="@Model.HomeId" asp-route-id="@Model.DemonstrationId">Ändra</a> |
        <a asp-action="Index">Gå tillbaka</a>
    </div>
    </div>
    <script src="~/js/menu.js"></script>

Views/Demonstrations/Edit.cshtml
@model project.Models.Demonstration

@{
    ViewData["Title"] = "Edit";
}

<div class="section">
    <div id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 high social">
                    <ul>
                        <li>
                            <i class="fab fa-instagram"></i>
                        </li>
                        <li><i class="fab fa-facebook"></i></li>
                    </ul>
                </div>
                <div class="col high main">
                    <h1>Ändra visning</h1>

                </div>
                <div class="col-sm-5 high">
                    <img src="~/images/man.png" alt="En man" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container marginTop">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DemonstrationId" />
                <div class="form-group">
                    <label asp-for="BookingTime" class="control-label"></label>
                    <input asp-for="BookingTime" class="form-control" />
                    <span asp-validation-for="BookingTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BookingDate" class="control-label"></label>
                    <input asp-for="BookingDate" class="form-control" />
                    <span asp-validation-for="BookingDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HomeId" class="control-label">Objektets adress</label>
                    <input type="hidden" asp-for="HomeId" class="form-control" />
                    @{ foreach (var item in ViewBag.home)
                        {@item
                    }
                    }
                    <span asp-validation-for="HomeId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Spara" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Gå tillbaka</a>
    </div>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
    <script src="~/js/menu.js"></script>

Views/Demonstrations/Index.cshtml
@model IEnumerable<project.Models.Demonstration>

@{
    ViewData["Title"] = "Visningar";
}

<div class="section">
    <div id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 high social">
                    <ul>
                        <li>
                            <i class="fab fa-instagram"></i>
                        </li>
                        <li><i class="fab fa-facebook"></i></li>
                    </ul>
                </div>
                <div class="col high main">
                    <h1>Visningar</h1>

                </div>
                <div class="col-sm-5 high">
                    <img src="~/images/man.png" alt="En man" />
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container marginTop">




    <p>
        <a class="btn-primary" asp-action="Create">Lägg till visning </a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BookingDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookingTime)
                </th>


                <th>
                    @Html.DisplayNameFor(model => model.HomeId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookingDate)
                    </td>
                    <td>

                        @Html.DisplayFor(modelItem => item.BookingTime)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.HomeId)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-homeId="@item.HomeId" asp-route-id="@item.DemonstrationId">Ändra</a> |

                        <a asp-action="Index" asp-controller="Persons" asp-route-homeId="@item.HomeId">Se inbokade personer</a> |
                        <a asp-action="Create" asp-controller="Persons" asp-route-homeId="@item.HomeId">Lägg till person</a> |
                        <a asp-action="Delete" asp-route-id="@item.DemonstrationId">Radera</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/js/menu.js"></script>